<?php

$sql_cmds[] = '
create global temporary table tmp_children (
   id                   INTEGER
)
   on commit preserve rows
';

$sql_cmds[] = '
create global temporary table tmp_id_collector (
   id                   INTEGER
)
   on commit preserve rows
';

$sql_cmds[] = '
create index idx_tmp_id on tmp_id_collector (
   id ASC
)
';

$sql_cmds[] = '
create table v1_attachment (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   post_id              INTEGER               not null,
   nr                   INTEGER               not null,
   name                 VARCHAR2(700 CHAR),
   origin_name          VARCHAR2(700 CHAR),
   type                 VARCHAR2(255),
   deleted              SMALLINT             default 0  not null,
   user_id              INTEGER,
   favourite            SMALLINT             default 0  not null,
   last_post_id         INTEGER               not null,
   constraint PK_V1_ATTACHMENT primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_attachment_unq on v1_attachment (
   post_id ASC,
   nr ASC
)
';

$sql_cmds[] = '
create index v1_attachment_name_idx on v1_attachment (
   name ASC
)
';

$sql_cmds[] = '
create index v1_attachment_type_idx on v1_attachment (
   type ASC
)
';

$sql_cmds[] = '
create index v1_attachment_user_idx on v1_attachment (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_attachment_favourite_idx on v1_attachment (
   favourite ASC
)
';

$sql_cmds[] = '
create index v1_attachment_last_post_idx on v1_attachment (
   last_post_id ASC
)
';

$sql_cmds[] = '
create table v1_auto_saved (
   topic_id             INTEGER               not null,
   read_marker          VARCHAR2(255)         not null,
   dt                   TIMESTAMP             not null,
   text_content         CLOB
)
';

$sql_cmds[] = '
create index v1_auto_saved_tid_idx on v1_auto_saved (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_auto_saved_dt_idx on v1_auto_saved (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_auto_saved_rm_idx on v1_auto_saved (
   read_marker ASC
)
';

$sql_cmds[] = '
create table v1_banned_ips (
   ip                   VARCHAR2(250)         not null,
   banned_until         TIMESTAMP             not null,
   hits                 INTEGER               not null,
   hit_limit            INTEGER              default 0  not null,
   check_period         INTEGER              default 60  not null,
   atype                VARCHAR2(255),
   statistics_request   INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create index v1_banned_ips_idx on v1_banned_ips (
   ip ASC
)
';

$sql_cmds[] = '
create table v1_browser_daily_statistics (
   dt                   DATE                  not null,
   browser              VARCHAR2(250 CHAR),
   os                   VARCHAR2(250 CHAR),
   bot                  VARCHAR2(250 CHAR),
   read_marker          VARCHAR2(255),
   bot_hits_count       INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create index v1_brwr_dstatistics_dt_idx on v1_browser_daily_statistics (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_brwr_dstatistics_brwr_idx on v1_browser_daily_statistics (
   browser ASC
)
';

$sql_cmds[] = '
create index v1_brwr_dstatistics_os_idx on v1_browser_daily_statistics (
   os ASC
)
';

$sql_cmds[] = '
create index v1_brwr_dstatistics_bot_idx on v1_browser_daily_statistics (
   bot ASC
)
';

$sql_cmds[] = '
create index v1_brwr_dstatistics_rm_idx on v1_browser_daily_statistics (
   read_marker ASC
)
';

$sql_cmds[] = '
create table v1_cache_invalidation (
   new_dt               TIMESTAMP
)
';

$sql_cmds[] = '
create table v1_daily_statistics (
   user_id              INTEGER               not null,
   forum_id             INTEGER               not null,
   dt                   DATE                  not null,
   hits_count           INTEGER              default 0  not null,
   bot_hits_count       INTEGER              default 0  not null,
   post_count           INTEGER              default 0  not null,
   time_online          INTEGER              default 0  not null,
   bot                  VARCHAR2(250 CHAR)    not null
)
';

$sql_cmds[] = '
create unique index v1_daily_statistics_unq on v1_daily_statistics (
   user_id ASC,
   forum_id ASC,
   dt ASC,
   bot ASC
)
';

$sql_cmds[] = '
create index v1_daily_statistics_dt_idx on v1_daily_statistics (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_daily_statistics_user_idx on v1_daily_statistics (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_daily_statistics_forum_idx on v1_daily_statistics (
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_daily_statistics_bot_idx on v1_daily_statistics (
   bot ASC
)
';

$sql_cmds[] = '
create table v1_dual (
   dummy_val            SMALLINT             default 0  not null
)
';

$sql_cmds[] = '
create table v1_events (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   event_time           TIMESTAMP             not null,
   event_code           VARCHAR2(255)         not null,
   params               CLOB,
   author_name          VARCHAR2(255 CHAR),
   author_id            INTEGER,
   post_id              INTEGER,
   is_new               SMALLINT             default 1  not null,
   todo                 SMALLINT             default 0  not null,
   user_id              INTEGER               not null,
   redundant            SMALLINT             default 0  not null,
   topic_name           VARCHAR2(1000 CHAR),
   topic_id             INTEGER,
   forum_name           VARCHAR2(255 CHAR),
   forum_id             INTEGER,
   note                 CLOB,
   source_topic_name    VARCHAR2(1000 CHAR),
   source_topic_id      INTEGER,
   constraint PK_V1_EVENTS primary key (id)
)
';

$sql_cmds[] = '
create index v1_events_evtime_idx on v1_events (
   event_time ASC
)
';

$sql_cmds[] = '
create index v1_events_user_id_idx on v1_events (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_events_post_id_idx on v1_events (
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_events_redundant_idx on v1_events (
   redundant ASC
)
';

$sql_cmds[] = '
create index v1_events_todo_idx on v1_events (
   todo ASC
)
';

$sql_cmds[] = '
create index v1_events_code_idx on v1_events (
   event_code ASC
)
';

$sql_cmds[] = '
create index v1_events_author_name_idx on v1_events (
   author_name ASC
)
';

$sql_cmds[] = '
create index v1_events_topic_id_idx on v1_events (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_events_src_topic_id_idx on v1_events (
   source_topic_id ASC
)
';

$sql_cmds[] = '
create index v1_events_forum_id_idx on v1_events (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_favourite_posts (
   post_id              INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_favourite_posts_unq on v1_favourite_posts (
   post_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_favourite_posts_post_id_idx on v1_favourite_posts (
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_favourite_posts_user_id_idx on v1_favourite_posts (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_favourite_topics (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_fav_topics_unq on v1_favourite_topics (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_fav_topics_topic_id_idx on v1_favourite_topics (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_fav_topics_user_id_idx on v1_favourite_topics (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_forum (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   name                 VARCHAR2(255 CHAR)    not null,
   protected_by_password SMALLINT             default 0  not null,
   password             VARCHAR2(255 CHAR),
   creation_date        TIMESTAMP             not null,
   restricted_access    SMALLINT             default 0  not null,
   allow_edit           SMALLINT             default 0  not null,
   no_guests            SMALLINT             default 0  not null,
   user_posting_as_guest SMALLINT             default 0  not null,
   restricted_guest_mode SMALLINT             default 0  not null,
   hide_from_robots     SMALLINT             default 0  not null,
   description          VARCHAR2(500 CHAR),
   deleted              SMALLINT             default 0  not null,
   closed               SMALLINT             default 0  not null,
   sort_order           INTEGER              default 0  not null,
   access_duration      INTEGER,
   access_message_count INTEGER,
   stringent_rules      SMALLINT             default 0  not null,
   disable_ignore       SMALLINT             default 0  not null,
   forum_group_id       INTEGER,
   constraint PK_V1_FORUM primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_forum_name_unq on v1_forum (
   name ASC
)
';

$sql_cmds[] = '
create index v1_forum_is_deleted_idx on v1_forum (
   deleted ASC
)
';

$sql_cmds[] = '
create index v1_forum_protected_by_pwd_idx on v1_forum (
   protected_by_password ASC
)
';

$sql_cmds[] = '
create index v1_forum_access_idx on v1_forum (
   restricted_access ASC
)
';

$sql_cmds[] = '
create table v1_forum_blocked (
   block_expires        TIMESTAMP,
   user_id              INTEGER               not null,
   forum_id             INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_forum_blocked_unq on v1_forum_blocked (
   user_id ASC,
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_blocked_user_id_idx on v1_forum_blocked (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_blocked_forum_id_idx on v1_forum_blocked (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_forum_group (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   name                 VARCHAR2(255 CHAR)    not null,
   sort_order           INTEGER              default 0  not null,
   constraint PK_V1_FORUM_GROUP primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_forum_group_name_unq on v1_forum_group (
   name ASC
)
';

$sql_cmds[] = '
create table v1_forum_hits (
   forum_id             INTEGER,
   topic_id             INTEGER,
   dt                   TIMESTAMP             not null,
   user_id              INTEGER,
   hits_count           INTEGER              default 0  not null,
   duration             INTEGER              default 0  not null,
   guest_name           VARCHAR2(250 CHAR),
   user_agent           VARCHAR2(700 CHAR),
   referrer             VARCHAR2(700),
   uri                  VARCHAR2(2000 CHAR),
   ip                   VARCHAR2(250),
   browser              VARCHAR2(250 CHAR),
   os                   VARCHAR2(250 CHAR),
   bot                  VARCHAR2(250 CHAR),
   read_marker          VARCHAR2(255),
   statistics_request   INTEGER              default 0  not null,
   headers              CLOB
)
';

$sql_cmds[] = '
create index v1_forum_hits_forum_idx on v1_forum_hits (
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_dt_idx on v1_forum_hits (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_user_idx on v1_forum_hits (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_topic_idx on v1_forum_hits (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_ua_idx on v1_forum_hits (
   user_agent ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_rm_idx on v1_forum_hits (
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_guest_name_idx on v1_forum_hits (
   guest_name ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_ip_idx on v1_forum_hits (
   ip ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_bot_idx on v1_forum_hits (
   bot ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_browser_idx on v1_forum_hits (
   browser ASC
)
';

$sql_cmds[] = '
create index v1_forum_hits_os_idx on v1_forum_hits (
   os ASC
)
';

$sql_cmds[] = '
create table v1_forum_member (
   user_id              INTEGER               not null,
   forum_id             INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_forum_member_unq on v1_forum_member (
   user_id ASC,
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_member_user_id_idx on v1_forum_member (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_member_forum_id_idx on v1_forum_member (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_forum_moderator (
   user_id              INTEGER               not null,
   forum_id             INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_forum_moderator_unq on v1_forum_moderator (
   user_id ASC,
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_forum_moderator_user_id_idx on v1_forum_moderator (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_fo_moderator_forum_id_idx on v1_forum_moderator (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_forum_read_markers (
   read_marker          VARCHAR2(255)         not null,
   forum_id             INTEGER               not null,
   first_read_date      TIMESTAMP,
   last_activity        TIMESTAMP,
   first_activity       TIMESTAMP,
   ip                   VARCHAR2(250)
)
';

$sql_cmds[] = '
create unique index v1_forum_read_markers_fmrm_idx on v1_forum_read_markers (
   read_marker ASC,
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_for_read_mark_lastact_idx on v1_forum_read_markers (
   last_activity ASC
)
';

$sql_cmds[] = '
create index v1_forum_read_markers_rm_idx on v1_forum_read_markers (
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_forum_read_markers_frdt_idx on v1_forum_read_markers (
   first_read_date ASC
)
';

$sql_cmds[] = '
create table v1_forum_statistics (
   forum_id             INTEGER               not null,
   topic_count          INTEGER              default 0  not null,
   topic_count_total    INTEGER              default 0  not null,
   last_message_date    TIMESTAMP,
   last_message_id      INTEGER
)
';

$sql_cmds[] = '
create unique index v1_forum_statistics_unq on v1_forum_statistics (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_found_post_cache (
   post_id              INTEGER               not null,
   topic_id             INTEGER               not null,
   session_id           VARCHAR2(255)         not null,
   dt                   TIMESTAMP             not null,
   search_hash          VARCHAR2(255)
)
';

$sql_cmds[] = '
create index v1_fnd_post_cache_session_idx on v1_found_post_cache (
   session_id ASC
)
';

$sql_cmds[] = '
create index v1_found_post_cache_post_idx on v1_found_post_cache (
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_found_post_cache_topic_idx on v1_found_post_cache (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_found_post_cache_hash_idx on v1_found_post_cache (
   search_hash ASC
)
';

$sql_cmds[] = '
create index v1_found_post_cache_dt_idx on v1_found_post_cache (
   dt ASC
)
';

$sql_cmds[] = '
create table v1_found_topic_cache (
   topic_id             INTEGER               not null,
   session_id           VARCHAR2(255)         not null,
   dt                   TIMESTAMP             not null,
   search_hash          VARCHAR2(255)
)
';

$sql_cmds[] = '
create index v1_fnd_topic_cache_session_idx on v1_found_topic_cache (
   session_id ASC
)
';

$sql_cmds[] = '
create index v1_found_topic_cache_topic_idx on v1_found_topic_cache (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_found_topic_cache_hash_idx on v1_found_topic_cache (
   search_hash ASC
)
';

$sql_cmds[] = '
create index v1_found_topic_cache_dt_idx on v1_found_topic_cache (
   dt ASC
)
';

$sql_cmds[] = '
create table v1_hide_guest_avatars (
   user_id              INTEGER               not null,
   avatar               VARCHAR2(250 CHAR)    not null
)
';

$sql_cmds[] = '
create unique index v1_hide_guest_avatars_unq on v1_hide_guest_avatars (
   user_id ASC,
   avatar ASC
)
';

$sql_cmds[] = '
create table v1_hide_profile (
   user_id              INTEGER               not null,
   hidden_user_id       INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_hide_profile_unq on v1_hide_profile (
   user_id ASC,
   hidden_user_id ASC
)
';

$sql_cmds[] = '
create table v1_ignore_history (
   user_id              INTEGER               not null,
   ignored_user_id      INTEGER               not null,
   exclude_date         TIMESTAMP             not null
)
';

$sql_cmds[] = '
create unique index v1_ignore_history_unq on v1_ignore_history (
   user_id ASC,
   ignored_user_id ASC
)
';

$sql_cmds[] = '
create table v1_ignored_forums (
   forum_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_ignored_forums_unq on v1_ignored_forums (
   forum_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_ignored_forums_user_id_idx on v1_ignored_forums (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_ignored_forums_forum_id_idx on v1_ignored_forums (
   forum_id ASC
)
';

$sql_cmds[] = '
create table v1_ignored_guests (
   user_id              INTEGER               not null,
   guest_name           VARCHAR2(255 CHAR)    not null,
   whitelist            SMALLINT             default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_ignored_guests_unq on v1_ignored_guests (
   guest_name ASC,
   user_id ASC,
   whitelist ASC
)
';

$sql_cmds[] = '
create index v1_ignored_guests_name_idx on v1_ignored_guests (
   guest_name ASC
)
';

$sql_cmds[] = '
create index v1_ignored_guests_user_id_idx on v1_ignored_guests (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_ignored_topics (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null,
   auto_ignored         SMALLINT             default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_ignored_topic_unq on v1_ignored_topics (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_ignored_topic_topic_id_idx on v1_ignored_topics (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_ignored_topic_user_id_idx on v1_ignored_topics (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_ignored_topics_archive (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null,
   auto_ignored         SMALLINT             default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_ignored_topics_archive_unq on v1_ignored_topics_archive (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_ignored_users (
   user_id              INTEGER               not null,
   ignored_user_id      INTEGER               not null,
   note                 CLOB
)
';

$sql_cmds[] = '
create unique index v1_ignored_users_unq on v1_ignored_users (
   user_id ASC,
   ignored_user_id ASC
)
';

$sql_cmds[] = '
create index v1_ignored_users_user_id_idx on v1_ignored_users (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_ign_users_ign_user_id_idx on v1_ignored_users (
   ignored_user_id ASC
)
';

$sql_cmds[] = '
create table v1_ip_blocked (
   ip                   VARCHAR2(250)         not null,
   block_expires        TIMESTAMP,
   tp                   VARCHAR2(10)         default \'IP\'  not null,
   block_reason         CLOB
)
';

$sql_cmds[] = '
create unique index v1_ip_blocked_unq on v1_ip_blocked (
   ip ASC
)
';

$sql_cmds[] = '
create table v1_ip_daily_statistics (
   dt                   DATE                  not null,
   ip                   VARCHAR2(250),
   country_code         VARCHAR2(10),
   country              VARCHAR2(250 CHAR),
   city                 VARCHAR2(250 CHAR),
   bot                  VARCHAR2(250 CHAR),
   is_tor               SMALLINT             default 0  not null,
   is_proxy             SMALLINT             default 0  not null,
   is_ipv6              SMALLINT             default 0  not null,
   read_marker          VARCHAR2(255),
   hits_count           INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create index v1_ip_daily_statistics_dt_idx on v1_ip_daily_statistics (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_ip_daily_statistics_ip_idx on v1_ip_daily_statistics (
   ip ASC
)
';

$sql_cmds[] = '
create index v1_ip_dstatistics_country_idx on v1_ip_daily_statistics (
   country ASC
)
';

$sql_cmds[] = '
create index v1_ip_dstatistics_city_idx on v1_ip_daily_statistics (
   city ASC
)
';

$sql_cmds[] = '
create table v1_ip_white_list (
   ip                   VARCHAR2(250)         not null
)
';

$sql_cmds[] = '
create table v1_load_statistics (
   dt                   TIMESTAMP             not null,
   url                  VARCHAR2(255 CHAR)    not null,
   user_name            VARCHAR2(255 CHAR),
   user_id              INTEGER,
   ip                   VARCHAR2(255),
   exec_time            INTEGER               not null,
   forum_rm_count       INTEGER              default 0  not null,
   topic_rm_count       INTEGER              default 0  not null,
   total_forum_rm_count INTEGER              default 0  not null,
   total_topic_rm_count INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create index v1_load_statistics_dt_idx on v1_load_statistics (
   dt ASC
)
';

$sql_cmds[] = '
create table v1_moderator_log (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   event_time           TIMESTAMP             not null,
   moderator_name       VARCHAR2(255 CHAR),
   moderator_id         INTEGER,
   action               VARCHAR2(255 CHAR),
   action_expires       TIMESTAMP,
   author_name          VARCHAR2(255 CHAR),
   author_id            INTEGER,
   ip                   VARCHAR2(250),
   post_id              INTEGER,
   topic_name           VARCHAR2(1000 CHAR),
   topic_id             INTEGER,
   forum_name           VARCHAR2(255 CHAR),
   forum_id             INTEGER,
   note                 CLOB,
   redundant            SMALLINT             default 0  not null,
   source_topic_name    VARCHAR2(1000 CHAR),
   source_topic_id      INTEGER,
   constraint PK_V1_MODERATOR_LOG primary key (id)
)
';

$sql_cmds[] = '
create index v1_mlog_mod_name_idx on v1_moderator_log (
   moderator_name ASC
)
';

$sql_cmds[] = '
create index v1_mlog_action_idx on v1_moderator_log (
   action ASC
)
';

$sql_cmds[] = '
create index v1_mlog_forum_id_idx on v1_moderator_log (
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_mlog_author_name_idx on v1_moderator_log (
   author_name ASC
)
';

$sql_cmds[] = '
create index v1_mlog_evt_tm_idx on v1_moderator_log (
   event_time ASC
)
';

$sql_cmds[] = '
create index v1_mlog_redundant_idx on v1_moderator_log (
   redundant ASC
)
';

$sql_cmds[] = '
create index v1_mlog_topic_id_idx on v1_moderator_log (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_mlog_src_topic_id_idx on v1_moderator_log (
   source_topic_id ASC
)
';

$sql_cmds[] = '
create table v1_morphology_dictionary (
   root                 VARCHAR2(255 CHAR)    not null,
   word                 VARCHAR2(255 CHAR)    not null
)
';

$sql_cmds[] = '
create index v1_morphology_dict_root_idx on v1_morphology_dictionary (
   root ASC
)
';

$sql_cmds[] = '
create index v1_morphology_dict_word_idx on v1_morphology_dictionary (
   word ASC
)
';

$sql_cmds[] = '
create table v1_pinned_topics (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_pinned_topics_unq on v1_pinned_topics (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_pinned_topics_topic_id_idx on v1_pinned_topics (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_pinned_topics_user_id_idx on v1_pinned_topics (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_poll_options (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   name                 VARCHAR2(700 CHAR)    not null,
   topic_id             INTEGER               not null,
   constraint PK_V1_POLL_OPTIONS primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_poll_options_unq on v1_poll_options (
   name ASC,
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_poll_options_topic_id_idx on v1_poll_options (
   topic_id ASC
)
';

$sql_cmds[] = '
create table v1_poll_user_answers (
   tm                   TIMESTAMP,
   user_id              INTEGER               not null,
   option_id            INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_poll_uanswers_unq on v1_poll_user_answers (
   user_id ASC,
   option_id ASC
)
';

$sql_cmds[] = '
create index v1_poll_uanswers_user_id_idx on v1_poll_user_answers (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_poll_uanswers_option_id_idx on v1_poll_user_answers (
   option_id ASC
)
';

$sql_cmds[] = '
create table v1_post (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   user_id              INTEGER,
   author               VARCHAR2(255 CHAR)    not null,
   creation_date        TIMESTAMP             not null,
   pinned               SMALLINT             default 0  not null,
   deleted              SMALLINT             default 0  not null,
   text_content         CLOB,
   html_content         CLOB,
   searchable_content   CLOB,
   has_picture          SMALLINT             default 0  not null,
   has_audio            SMALLINT             default 0  not null,
   has_telegram         SMALLINT             default 0  not null,
   has_video            SMALLINT             default 0  not null,
   has_link             SMALLINT             default 0  not null,
   has_code             SMALLINT             default 0  not null,
   has_attachment       SMALLINT             default 0  not null,
   has_attachment_ref   SMALLINT             default 0  not null,
   read_marker          VARCHAR2(255),
   ip                   VARCHAR2(250),
   last_updated_by      VARCHAR2(255 CHAR),
   last_updated         TIMESTAMP,
   self_edited          SMALLINT             default 0  not null,
   last_warned_by       VARCHAR2(255 CHAR),
   last_warning         CLOB,
   bb_parser_version    INTEGER              default 1  not null,
   topic_id             INTEGER               not null,
   user_marker          VARCHAR2(255),
   user_agent           VARCHAR2(700 CHAR),
   is_comment           SMALLINT             default 0  not null,
   is_adult             SMALLINT             default 0  not null,
   is_system            SMALLINT             default 0  not null,
   ref                  INTEGER,
   constraint PK_V1_POST primary key (id)
)
';

$sql_cmds[] = '
BEGIN
  CTX_DDL.CREATE_PREFERENCE(\'forum_lexer\', \'WORLD_LEXER\');
  CTX_DDL.CREATE_STOPLIST(\'forum_stoplist\', \'BASIC_STOPLIST\');
END
';

$sql_cmds[] = '
CREATE INDEX v1_post_ftx ON v1_post(searchable_content)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS (\'LEXER forum_lexer STOPLIST forum_stoplist SYNC (ON COMMIT)\')
';

$sql_cmds[] = '
create index v1_post_is_deleted_idx on v1_post (
   deleted ASC
)
';

$sql_cmds[] = '
create index v1_post_user_id_idx on v1_post (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_post_topic_id_idx on v1_post (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_post_has_attachment_idx on v1_post (
   has_attachment ASC
)
';

$sql_cmds[] = '
create index v1_post_has_attachment_ref_idx on v1_post (
   has_attachment_ref ASC
)
';

$sql_cmds[] = '
create index v1_post_ip_idx on v1_post (
   ip ASC
)
';

$sql_cmds[] = '
create index v1_post_rm_idx on v1_post (
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_post_author_idx on v1_post (
   author ASC
)
';

$sql_cmds[] = '
create index v1_post_creation_date_idx on v1_post (
   creation_date ASC
)
';

$sql_cmds[] = '
create index v1_post_is_pinned_idx on v1_post (
   pinned ASC
)
';

$sql_cmds[] = '
create index v1_post_user_marker_idx on v1_post (
   user_marker ASC
)
';

$sql_cmds[] = '
create index v1_post_has_telegram_idx on v1_post (
   has_telegram ASC
)
';

$sql_cmds[] = '
create index v1_post_has_video_idx on v1_post (
   has_video ASC
)
';

$sql_cmds[] = '
create index v1_post_has_audio_idx on v1_post (
   has_audio ASC
)
';

$sql_cmds[] = '
create index v1_post_has_link_idx on v1_post (
   has_link ASC
)
';

$sql_cmds[] = '
create index v1_post_has_code_idx on v1_post (
   has_code ASC
)
';

$sql_cmds[] = '
create index v1_post_is_comment_idx on v1_post (
   is_comment ASC
)
';

$sql_cmds[] = '
create index v1_post_is_adult_idx on v1_post (
   is_adult ASC
)
';

$sql_cmds[] = '
create index v1_post_has_picture_idx on v1_post (
   has_picture ASC
)
';

$sql_cmds[] = '
create index v1_post_ref_idx on v1_post (
   ref ASC
)
';

$sql_cmds[] = '
create table v1_post_hierarchy (
   parent_post_id       INTEGER               not null,
   reply_post_id        INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_post_hierarchy_unq on v1_post_hierarchy (
   parent_post_id ASC,
   reply_post_id ASC
)
';

$sql_cmds[] = '
create index v1_post_hierarchy_ppost_id on v1_post_hierarchy (
   parent_post_id ASC
)
';

$sql_cmds[] = '
create index v1_post_hierarchy_rpost_id on v1_post_hierarchy (
   reply_post_id ASC
)
';

$sql_cmds[] = '
create table v1_post_history (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   dt                   TIMESTAMP             not null,
   author               VARCHAR2(255 CHAR),
   self_edited          SMALLINT             default 0  not null,
   text_content         CLOB,
   html_content         CLOB,
   post_id              INTEGER               not null,
   constraint PK_V1_POST_HISTORY primary key (id)
)
';

$sql_cmds[] = '
create index v1_post_history_post_id_idx on v1_post_history (
   post_id ASC
)
';

$sql_cmds[] = '
create table v1_post_rating (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   rating               INTEGER               not null,
   dt                   TIMESTAMP,
   post_id              INTEGER               not null,
   user_id              INTEGER               not null,
   rater_ignored        SMALLINT             default 0  not null,
   constraint PK_V1_POST_RATING primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_post_rating_unq on v1_post_rating (
   post_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_post_rating_post_idx on v1_post_rating (
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_post_rating_user_idx on v1_post_rating (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_post_rating_raiting_idx on v1_post_rating (
   rating ASC
)
';

$sql_cmds[] = '
create table v1_post_statistics (
   post_id              INTEGER               not null,
   like_count           INTEGER              default 0  not null,
   dislike_count        INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_post_statistics_unq on v1_post_statistics (
   post_id ASC
)
';

$sql_cmds[] = '
create table v1_post_subscription (
   post_id              INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_post_subscr_unq on v1_post_subscription (
   post_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_post_subscr_post_id_idx on v1_post_subscription (
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_post_subscr_user_id_idx on v1_post_subscription (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_private_topics (
   last_visit_date      TIMESTAMP,
   topic_id             INTEGER               not null,
   participant_id       INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_priv_topics_unq on v1_private_topics (
   topic_id ASC,
   participant_id ASC
)
';

$sql_cmds[] = '
create index v1_priv_topics_topic_id_idx on v1_private_topics (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_priv_topics_particip_id_idx on v1_private_topics (
   participant_id ASC
)
';

$sql_cmds[] = '
create table v1_protected_guests (
   guest_name           VARCHAR2(255 CHAR)    not null,
   guest_name_hash      VARCHAR2(255 CHAR)
)
';

$sql_cmds[] = '
create unique index v1_protected_guests_unq on v1_protected_guests (
   guest_name ASC
)
';

$sql_cmds[] = '
create index v1_protected_guests_hash_idx on v1_protected_guests (
   guest_name_hash ASC
)
';

$sql_cmds[] = '
create table v1_read_marker_activity (
   read_marker          VARCHAR2(255)         not null,
   last_activity        TIMESTAMP,
   first_activity       TIMESTAMP,
   ip                   VARCHAR2(250),
   author               VARCHAR2(255 CHAR),
   user_agent           VARCHAR2(500 CHAR),
   hits                 INTEGER              default 0  not null,
   current_name_start   TIMESTAMP,
   current_name_hits    INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_read_marker_activity_unq on v1_read_marker_activity (
   read_marker ASC
)
';

$sql_cmds[] = '
create table v1_reserved_names (
   user_name            VARCHAR2(255 CHAR)    not null,
   user_name_hash       VARCHAR2(255 CHAR)
)
';

$sql_cmds[] = '
create unique index v1_reserved_names_unq on v1_reserved_names (
   user_name ASC
)
';

$sql_cmds[] = '
create table v1_settings (
   moderator_log        VARCHAR2(100),
   default_sender       VARCHAR2(255 CHAR),
   receiver             VARCHAR2(255 CHAR),
   max_att_size         INTEGER,
   max_att_size_audiovideo INTEGER,
   max_messages_minute  INTEGER,
   max_messages_hour    INTEGER,
   max_messages_day     INTEGER,
   min_search_interval  INTEGER,
   whois_server         VARCHAR2(500 CHAR),
   hide_online_status   SMALLINT             default 0  not null,
   approval_required    SMALLINT             default 0  not null,
   delayed_reg_mailing  SMALLINT             default 0  not null,
   max_rates_hour       INTEGER,
   max_topics_day       INTEGER,
   rates_active         SMALLINT             default 0  not null,
   dislikes_active      SMALLINT             default 0  not null,
   dislikes_anonym      SMALLINT             default 0  not null,
   skin                 VARCHAR2(255),
   max_poll_options     INTEGER,
   max_user_name_symbols INTEGER,
   max_topic_name_symbols INTEGER,
   max_message_length   INTEGER,
   max_pinned_topics    INTEGER,
   max_private_members  INTEGER,
   block_tor_ips        SMALLINT             default 0  not null,
   celebration_active   SMALLINT             default 0  not null,
   mourning_active      SMALLINT             default 0  not null,
   snow_effect          SMALLINT             default 0  not null,
   hide_users_from_robots SMALLINT             default 0  not null,
   archive_mode         SMALLINT             default 0  not null,
   request_cookie_consent SMALLINT             default 0  not null,
   hash_ip_addresses    SMALLINT             default 0  not null
)
';

$sql_cmds[] = '
create table v1_topic (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   name                 VARCHAR2(700 CHAR)    not null,
   author               VARCHAR2(255 CHAR)    not null,
   creation_date        TIMESTAMP             not null,
   deleted              SMALLINT             default 0  not null,
   closed               SMALLINT             default 0  not null,
   pinned               SMALLINT             default 0  not null,
   read_marker          VARCHAR2(255),
   has_pinned_post      SMALLINT             default 0  not null,
   merged               INTEGER,
   is_poll              SMALLINT             default 0  not null,
   poll_comment         CLOB,
   poll_results_delayed SMALLINT             default 0  not null,
   no_guests            SMALLINT             default 0  not null,
   forum_id             INTEGER               not null,
   user_id              INTEGER,
   user_marker          VARCHAR2(255),
   is_private           SMALLINT             default 0  not null,
   publish_delay        SMALLINT             default 0  not null,
   profiled_topic       SMALLINT             default 0  not null,
   request_moderation   SMALLINT             default 0  not null,
   ref                  INTEGER,
   constraint PK_V1_TOPIC primary key (id)
)
';

$sql_cmds[] = '
CREATE INDEX v1_topic_ftx ON v1_topic(name)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS (\'LEXER forum_lexer STOPLIST forum_stoplist SYNC (ON COMMIT)\')
';

$sql_cmds[] = '
create index v1_topic_name_idx on v1_topic (
   name ASC
)
';

$sql_cmds[] = '
create index v1_topic_user_id_idx on v1_topic (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_forum_id_idx on v1_topic (
   forum_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_is_deleted_idx on v1_topic (
   deleted ASC
)
';

$sql_cmds[] = '
create index v1_topic_rm_idx on v1_topic (
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_topic_is_pinned_idx on v1_topic (
   pinned ASC
)
';

$sql_cmds[] = '
create index v1_topic_is_private_idx on v1_topic (
   is_private ASC
)
';

$sql_cmds[] = '
create index v1_topic_publish_delay_idx on v1_topic (
   publish_delay ASC
)
';

$sql_cmds[] = '
create index v1_topic_author_idx on v1_topic (
   author ASC
)
';

$sql_cmds[] = '
create index v1_topic_creation_date_idx on v1_topic (
   creation_date ASC
)
';

$sql_cmds[] = '
create index v1_topic_ref_idx on v1_topic (
   ref ASC
)
';

$sql_cmds[] = '
create table v1_topic_blocked (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_topic_blocked_unq on v1_topic_blocked (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_blocked_topic_id_idx on v1_topic_blocked (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_blocked_user_id_idx on v1_topic_blocked (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_topic_moderator (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_tmoderator_unq on v1_topic_moderator (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_tmoderator_topic_id_idx on v1_topic_moderator (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_tmoderator_user_id_idx on v1_topic_moderator (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_topic_participants (
   user_id              INTEGER               not null,
   topic_id             INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_topic_participants_unq on v1_topic_participants (
   user_id ASC,
   topic_id ASC
)
';

$sql_cmds[] = '
create table v1_topic_read_markers (
   topic_id             INTEGER               not null,
   read_marker          VARCHAR2(255)         not null,
   last_read_date       TIMESTAMP,
   ip                   VARCHAR2(250)
)
';

$sql_cmds[] = '
create unique index v1_topic_read_markers_tprm_idx on v1_topic_read_markers (
   topic_id ASC,
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_topic_read_markers_rm_idx on v1_topic_read_markers (
   read_marker ASC
)
';

$sql_cmds[] = '
create index v1_topic_read_markers_lrdt_idx on v1_topic_read_markers (
   last_read_date ASC
)
';

$sql_cmds[] = '
create table v1_topic_statistics (
   topic_id             INTEGER               not null,
   post_count           INTEGER              default 0  not null,
   post_count_total     INTEGER              default 0  not null,
   hits_count           INTEGER              default 0  not null,
   bot_hits_count       INTEGER              default 0  not null,
   last_message_date    TIMESTAMP,
   last_message_id      INTEGER
)
';

$sql_cmds[] = '
create unique index v1_topic_statistics_unq on v1_topic_statistics (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_statistics_lmid_idx on v1_topic_statistics (
   last_message_id ASC
)
';

$sql_cmds[] = '
create index v1_topic_statistics_lmdate_idx on v1_topic_statistics (
   last_message_date ASC
)
';

$sql_cmds[] = '
create table v1_topic_subscription (
   topic_id             INTEGER               not null,
   user_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_tsubscription_unq on v1_topic_subscription (
   topic_id ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_tsubscription_topic_id_idx on v1_topic_subscription (
   topic_id ASC
)
';

$sql_cmds[] = '
create index v1_tsubscription_user_id_idx on v1_topic_subscription (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_topic_view_history (
   user_id              INTEGER               not null,
   guest_name           VARCHAR2(255 CHAR)    not null,
   topic_id             INTEGER               not null,
   dt                   TIMESTAMP             not null,
   ip                   VARCHAR2(250)
)
';

$sql_cmds[] = '
create unique index v1_tview_history_unq on v1_topic_view_history (
   user_id ASC,
   topic_id ASC,
   guest_name ASC
)
';

$sql_cmds[] = '
create index v1_tview_history_user_idx on v1_topic_view_history (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_tview_history_dt_idx on v1_topic_view_history (
   dt ASC
)
';

$sql_cmds[] = '
create index v1_tview_history_gname_idx on v1_topic_view_history (
   guest_name ASC
)
';

$sql_cmds[] = '
create table v1_tor_ips (
   ip                   VARCHAR2(250)         not null,
   block_level          INTEGER              default 0  not null,
   refresh_date         TIMESTAMP
)
';

$sql_cmds[] = '
create unique index v1_tor_ips_unq on v1_tor_ips (
   ip ASC
)
';

$sql_cmds[] = '
create table v1_user (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   login                VARCHAR2(255 CHAR)    not null,
   password_hash        VARCHAR2(255 CHAR)    not null,
   user_name            VARCHAR2(255 CHAR)    not null,
   user_name_hash       VARCHAR2(255 CHAR),
   email                VARCHAR2(255 CHAR)    not null,
   email_hash           VARCHAR2(255 CHAR)    not null,
   hide_email           SMALLINT             default 1  not null,
   registration_date    TIMESTAMP             not null,
   last_visit_date      TIMESTAMP,
   last_post_date       TIMESTAMP,
   is_admin             SMALLINT             default 0  not null,
   message              VARCHAR2(500 CHAR),
   info                 CLOB,
   homepage             VARCHAR2(500 CHAR),
   signature            CLOB,
   api_active           SMALLINT             default 0  not null,
   api_token            VARCHAR2(100),
   pwd_reset_hash       VARCHAR2(255),
   pwd_reset_expire     TIMESTAMP,
   activation_hash      VARCHAR2(100),
   activation_expire    TIMESTAMP,
   activated            SMALLINT             default 0  not null,
   died                 SMALLINT             default 0  not null,
   autologin_hash       VARCHAR2(255 CHAR),
   blocked              SMALLINT             default 0  not null,
   self_blocked         SMALLINT             default 0  not null,
   block_expires        TIMESTAMP,
   block_reason         CLOB,
   hide_user_avatars    SMALLINT             default 0  not null,
   hide_user_info       SMALLINT             default 0  not null,
   hide_pictures        SMALLINT             default 0  not null,
   donot_hide_adult_pictures SMALLINT             default 0  not null,
   hide_ignored         SMALLINT             default 0  not null,
   location             VARCHAR2(255),
   hidden               SMALLINT             default 0  not null,
   send_notifications   SMALLINT             default 0  not null,
   donot_notify_on_rates SMALLINT             default 0  not null,
   no_private_messages  SMALLINT             default 0  not null,
   turnoff_personal_appeals SMALLINT             default 0  not null,
   turnoff_events       SMALLINT             default 0  not null,
   approved             SMALLINT             default 0  not null,
   read_marker          VARCHAR2(255)         not null,
   ip                   VARCHAR2(250),
   last_ip              VARCHAR2(250),
   ignore_guests_blacklist SMALLINT             default 0  not null,
   ignore_guests_whitelist SMALLINT             default 0  not null,
   ignore_new_guests    SMALLINT             default 0  not null,
   no_video_expand      SMALLINT             default 0  not null,
   logout               SMALLINT             default 0  not null,
   last_logout_date     TIMESTAMP,
   last_events_view_date TIMESTAMP,
   video_audio_blocked  SMALLINT             default 0  not null,
   attachments_blocked  SMALLINT             default 0  not null,
   rating_blocked       SMALLINT             default 0  not null,
   time_zone            VARCHAR2(255),
   privileged           SMALLINT             default 0  not null,
   privileged_topic_moderator SMALLINT             default 0  not null,
   notify_about_new_users SMALLINT             default 0  not null,
   notify_citation      SMALLINT             default 0  not null,
   skin                 VARCHAR2(255),
   skin_properties      CLOB,
   interface_language   VARCHAR2(50),
   global_ban_allowed   SMALLINT             default 0  not null,
   show_ip              SMALLINT             default 0  not null,
   notify_on_words      SMALLINT             default 0  not null,
   words_to_notify      CLOB,
   last_host            VARCHAR2(255 CHAR),
   custom_css           CLOB,
   custom_smiles        CLOB,
   ref                  INTEGER,
   email_changed        SMALLINT             default 0  not null,
   constraint PK_V1_USER primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_user_login_unq on v1_user (
   login ASC
)
';

$sql_cmds[] = '
create unique index v1_user_nickname_unq on v1_user (
   user_name ASC
)
';

$sql_cmds[] = '
create index v1_user_nickname_hash_idx on v1_user (
   user_name_hash ASC
)
';

$sql_cmds[] = '
create unique index v1_user_email_unq on v1_user (
   email_hash ASC
)
';

$sql_cmds[] = '
create index v1_user_autologin_hash_idx on v1_user (
   autologin_hash ASC
)
';

$sql_cmds[] = '
create index v1_user_pwd_reset_hash_idx on v1_user (
   pwd_reset_hash ASC
)
';

$sql_cmds[] = '
create index v1_user_block_expires_idx on v1_user (
   block_expires ASC
)
';

$sql_cmds[] = '
create unique index v1_user_read_marker_unq on v1_user (
   read_marker ASC
)
';

$sql_cmds[] = '
create table v1_user_comment (
   user_id              INTEGER               not null,
   commented_user_id    INTEGER               not null,
   note                 CLOB
)
';

$sql_cmds[] = '
create unique index v1_user_comment_unq on v1_user_comment (
   user_id ASC,
   commented_user_id ASC
)
';

$sql_cmds[] = '
create table v1_user_login_tries (
   login                VARCHAR2(250 CHAR)    not null,
   ip                   VARCHAR2(250)         not null,
   dt                   TIMESTAMP             not null
)
';

$sql_cmds[] = '
create index v1_user_login_tries_ip_idx on v1_user_login_tries (
   ip ASC
)
';

$sql_cmds[] = '
create table v1_user_statistics (
   user_id              INTEGER               not null,
   post_count           INTEGER              default 0  not null,
   like_count           INTEGER              default 0  not null,
   dislike_count        INTEGER              default 0  not null,
   topic_count          INTEGER              default 0  not null,
   time_online          INTEGER              default 0  not null
)
';

$sql_cmds[] = '
create unique index v1_user_statistics_unq on v1_user_statistics (
   user_id ASC
)
';

$sql_cmds[] = '
create table v1_user_subscription (
   user_id              INTEGER               not null,
   subscribed_user_id   INTEGER               not null,
   subscribed_user_name VARCHAR2(255 CHAR)    not null,
   tm                   TIMESTAMP             not null,
   last_view            TIMESTAMP
)
';

$sql_cmds[] = '
create unique index v1_user_subscription_unq on v1_user_subscription (
   user_id ASC,
   subscribed_user_id ASC,
   subscribed_user_name ASC
)
';

$sql_cmds[] = '
create index v1_user_subscription_usr_idx on v1_user_subscription (
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_usubscription_user_name_idx on v1_user_subscription (
   subscribed_user_name ASC
)
';

$sql_cmds[] = '
create index v1_user_subscription_usrid_idx on v1_user_subscription (
   subscribed_user_id ASC
)
';

$sql_cmds[] = '
create table v1_user_tag_post (
   tag_id               INTEGER               not null,
   post_id              INTEGER               not null
)
';

$sql_cmds[] = '
create unique index v1_user_tag_post_unq on v1_user_tag_post (
   tag_id ASC,
   post_id ASC
)
';

$sql_cmds[] = '
create index v1_user_tag_post_tag_id_idx on v1_user_tag_post (
   tag_id ASC
)
';

$sql_cmds[] = '
create index v1_user_tag_post_post_id_idx on v1_user_tag_post (
   post_id ASC
)
';

$sql_cmds[] = '
create table v1_user_tags (
   id                   INTEGER             
      generated by default as identity ( start with 1 nocycle noorder)  not null,
   name                 VARCHAR2(255 CHAR)    not null,
   user_id              INTEGER               not null,
   constraint PK_V1_USER_TAGS primary key (id)
)
';

$sql_cmds[] = '
create unique index v1_user_tags_unq on v1_user_tags (
   name ASC,
   user_id ASC
)
';

$sql_cmds[] = '
create index v1_user_tags_user_id_idx on v1_user_tags (
   user_id ASC
)
';

?>