CREATE USER &1 IDENTIFIED BY &2
  DEFAULT TABLESPACE &3
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON &3;

GRANT CONNECT, RESOURCE TO &1;
GRANT CREATE SESSION TO &1;
GRANT CREATE TABLE TO &1;
GRANT CREATE SEQUENCE TO &1;
GRANT CREATE PROCEDURE TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE TRIGGER TO &1;
GRANT CTXAPP TO &1;  
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO &1;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO &1;  

EXIT;